#!/usr/bin/env bash
# script installs an nginx web server

apt update
apt -y install nginx
ufw enable
ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
service nginx restart
