#!/usr/bin/env bash
# script installs an nginx web server

apt-get -y install nginx
service nginx start
ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
service nginx restart
