#!/usr/bin/env bash

apt-get update
apt-get -y install nginx

ufw allow 'Nginx HTTP'

sed -i '43i\\trewrite ^/redirect_me 301 permanent;' /etc/nginx/sites-available/default

echo "Ceci n'est pas une page\n" >> /var/www/html/error_404.html
sed -i '38i\error_page 404 /error_404.html;' /etc/nginx/sites-available/default

service nginx restart
