#!/usr/bin/env bash
# script that saves its pid to file and prints <message? indefinitely

echo $$ >> /var/run/myscript.pid
i=true

while [ $i ]
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "Y U no love me?!" SIGINT
	trap 'echo "I hate the kill command"; rm /var/run/myscript.pid' SIGTERM SIGQUIT
done
