#!/usr/bin/env bash
# print 'Best School' 10 times; after 9th iteration print hi
# then continue with the remainder of the iterations

i=1

while [ $i -le 10 ]
do
	echo "Best School"
	if [ $i -eq 9 ]
	then
		echo "Hi"
	fi
	i=$((i+1))
done
