#!/usr/bin/env bash
# prints 1 to 20 with while loop
# after 4, it prints 'bad luck from china'; after 9 'bad luck from japan'
# after 17 'bad luck from Italy'

i=1

while [ $i -le 20 ];
do
	case $i in
		4)
			echo $i 
			echo "bad luck from China"
			;;
			
		9)
			echo $i
			echo "bad luck from Japan"
			;;
		17)
			echo $i
			echo "bad luck from Italy"
			;;
		*)
			echo $i
			;;
	esac
	i=$((i+1))
done
